"""crate facilityinfo

Revision ID: 0b589027fd80
Revises: 22f1b77bd2f3
Create Date: 2025-12-26 22:04:56.883374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b589027fd80'
down_revision = '22f1b77bd2f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('facility_type', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('accepted_age', sa.String(length=100), nullable=True),
    sa.Column('hours_weekday', sa.String(length=50), nullable=True),
    sa.Column('hours_saturday', sa.String(length=50), nullable=True),
    sa.Column('hours_holiday', sa.String(length=50), nullable=True),
    sa.Column('staff_teacher', sa.Integer(), nullable=True),
    sa.Column('staff_support', sa.Integer(), nullable=True),
    sa.Column('staff_nutrition', sa.Integer(), nullable=True),
    sa.Column('staff_cook', sa.Integer(), nullable=True),
    sa.Column('staff_nurse', sa.Integer(), nullable=True),
    sa.Column('staff_office', sa.Integer(), nullable=True),
    sa.Column('childcare_fee_text', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facility_info')
    # ### end Alembic commands ###
