"""update facilityinfo

Revision ID: 26a4e7bd92e2
Revises: 52680bc9745d
Create Date: 2025-12-27 23:54:26.221938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a4e7bd92e2'
down_revision = '52680bc9745d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('facility_info', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
    #     batch_op.add_column(sa.Column('facility_type', sa.String(length=100), nullable=False))
    #     batch_op.add_column(sa.Column('phone', sa.String(length=100), nullable=True))
    #     batch_op.add_column(sa.Column('accepted_age', sa.String(length=100), nullable=True))
    #     batch_op.add_column(sa.Column('postal_code', sa.String(length=8), nullable=True))
    #     batch_op.add_column(sa.Column('hours_weekday', sa.String(length=50), nullable=True))
    #     batch_op.add_column(sa.Column('hours_saturday', sa.String(length=50), nullable=True))
    #     batch_op.add_column(sa.Column('hours_holiday', sa.String(length=50), nullable=True))
    #     batch_op.add_column(sa.Column('staff_teacher', sa.Integer(), nullable=True))
    #     batch_op.add_column(sa.Column('staff_support', sa.Integer(), nullable=True))
    #     batch_op.add_column(sa.Column('staff_nutrition', sa.Integer(), nullable=True))
    #     batch_op.add_column(sa.Column('staff_cook', sa.Integer(), nullable=True))
    #     batch_op.add_column(sa.Column('staff_nurse', sa.Integer(), nullable=True))
    #     batch_op.add_column(sa.Column('staff_office', sa.Integer(), nullable=True))
    #     batch_op.add_column(sa.Column('childcare_fee_text', sa.String(length=100), nullable=True))
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('facility_info', schema=None) as batch_op:
    #     batch_op.drop_column('childcare_fee_text')
    #     batch_op.drop_column('staff_office')
    #     batch_op.drop_column('staff_nurse')
    #     batch_op.drop_column('staff_cook')
    #     batch_op.drop_column('staff_nutrition')
    #     batch_op.drop_column('staff_support')
    #     batch_op.drop_column('staff_teacher')
    #     batch_op.drop_column('hours_holiday')
    #     batch_op.drop_column('hours_saturday')
    #     batch_op.drop_column('hours_weekday')
    #     batch_op.drop_column('postal_code')
    #     batch_op.drop_column('accepted_age')
    #     batch_op.drop_column('phone')
    #     batch_op.drop_column('facility_type')
    #     batch_op.drop_column('name')
    pass

    # ### end Alembic commands ###
