"""update facilityinfo

Revision ID: 52680bc9745d
Revises: a8bb0e37f690
Create Date: 2025-12-27 23:52:48.687784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52680bc9745d'
down_revision = 'a8bb0e37f690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facility_info', schema=None) as batch_op:
        batch_op.drop_column('staff_office')
        batch_op.drop_column('staff_nutrition')
        batch_op.drop_column('accepted_age')
        batch_op.drop_column('childcare_fee_text')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('staff_cook')
        batch_op.drop_column('staff_teacher')
        batch_op.drop_column('name')
        batch_op.drop_column('phone')
        batch_op.drop_column('facility_type')
        batch_op.drop_column('staff_support')
        batch_op.drop_column('hours_weekday')
        batch_op.drop_column('hours_saturday')
        batch_op.drop_column('staff_nurse')
        batch_op.drop_column('hours_holiday')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facility_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours_holiday', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('staff_nurse', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hours_saturday', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hours_weekday', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('staff_support', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('facility_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('staff_teacher', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('staff_cook', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('childcare_fee_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('accepted_age', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('staff_nutrition', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('staff_office', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
