"""update facilityinfo

Revision ID: ae16eeb08acb
Revises: 0b589027fd80
Create Date: 2025-12-27 23:43:24.986676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae16eeb08acb'
down_revision = '0b589027fd80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facility_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postal_code', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facility_info', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('postal_code')

    # ### end Alembic commands ###
